# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.22)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS TKDraw TKTopTest TKOpenGlTest TKViewerTest TKXSDRAW TKDCAF TKXDEDRAW TKTObjDRAW TKQADraw)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target TKDraw
add_library(TKDraw SHARED IMPORTED)

set_target_properties(TKDraw PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/inc"
  INTERFACE_LINK_LIBRARIES "TKernel;TKG2d;TKGeomBase;TKG3d;TKMath;TKBRep;TKGeomAlgo;TKShHealing;TKMesh;TKService;TKHLR;TKTopAlgo;C:/D/gitfile/occt/3rd/tcltk-86-64/lib/tcl86.lib;C:/D/gitfile/occt/3rd/tcltk-86-64/lib/tk86.lib;gdi32.lib;advapi32.lib;user32.lib;shell32.lib"
)

# Create imported target TKTopTest
add_library(TKTopTest SHARED IMPORTED)

set_target_properties(TKTopTest PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/inc"
  INTERFACE_LINK_LIBRARIES "TKBRep;TKGeomAlgo;TKTopAlgo;TKernel;TKMath;TKBO;TKG2d;TKG3d;TKDraw;TKHLR;TKGeomBase;TKMesh;TKService;TKV3d;TKFillet;TKPrim;TKBool;TKOffset;TKFeat;TKShHealing"
)

# Create imported target TKOpenGlTest
add_library(TKOpenGlTest SHARED IMPORTED)

set_target_properties(TKOpenGlTest PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/inc"
  INTERFACE_LINK_LIBRARIES "TKernel;TKMath;TKDraw;TKOpenGl;TKService;TKV3d;TKViewerTest;opengl32.lib"
)

# Create imported target TKViewerTest
add_library(TKViewerTest SHARED IMPORTED)

set_target_properties(TKViewerTest PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/inc"
  INTERFACE_LINK_LIBRARIES "TKGeomBase;TKFillet;TKBRep;TKTopAlgo;TKHLR;TKernel;TKMath;TKService;TKShHealing;TKBool;TKPrim;TKGeomAlgo;TKG2d;TKTopTest;TKG3d;TKOffset;TKMesh;TKV3d;TKDraw;C:/D/gitfile/occt/3rd/tcltk-86-64/lib/tcl86.lib;user32.lib;gdi32.lib;C:/D/gitfile/occt/3rd/freetype-2.5.5-vc14-64/lib/freetype.lib"
)

# Create imported target TKXSDRAW
add_library(TKXSDRAW SHARED IMPORTED)

set_target_properties(TKXSDRAW PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/inc"
  INTERFACE_LINK_LIBRARIES "TKBRep;TKV3d;TKMath;TKernel;TKService;TKXSBase;TKMeshVS;TKG3d;TKViewerTest;TKG2d;TKSTEPBase;TKTopAlgo;TKGeomBase;TKGeomAlgo;TKMesh;TKDraw;TKSTEP;TKIGES;TKSTL;TKVRML;TKLCAF;TKDCAF;TKXCAF;TKRWMesh"
)

# Create imported target TKDCAF
add_library(TKDCAF SHARED IMPORTED)

set_target_properties(TKDCAF PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/inc"
  INTERFACE_LINK_LIBRARIES "TKGeomBase;TKBRep;TKGeomAlgo;TKernel;TKMath;TKG2d;TKG3d;TKDraw;TKCDF;TKV3d;TKService;TKLCAF;TKFillet;TKTopAlgo;TKPrim;TKBool;TKBO;TKCAF;TKVCAF;TKViewerTest;TKStd;TKStdL;TKBin;TKBinL;TKXml;TKXmlL"
)

# Create imported target TKXDEDRAW
add_library(TKXDEDRAW SHARED IMPORTED)

set_target_properties(TKXDEDRAW PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/inc"
  INTERFACE_LINK_LIBRARIES "TKXDE;TKCDF;TKBRep;TKXCAF;TKernel;TKIGES;TKV3d;TKMath;TKService;TKXSBase;TKG2d;TKCAF;TKVCAF;TKDraw;TKTopAlgo;TKLCAF;TKG3d;TKRWMesh;TKSTEPBase;TKSTEP;TKSTL;TKMesh;TKXSDRAW;TKXDECascade;TKXDEIGES;TKXDESTEP;TKDCAF;TKViewerTest;TKBinXCAF;TKXmlXCAF;TKVRML"
)

# Create imported target TKTObjDRAW
add_library(TKTObjDRAW SHARED IMPORTED)

set_target_properties(TKTObjDRAW PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/inc"
  INTERFACE_LINK_LIBRARIES "TKernel;TKCDF;TKLCAF;TKTObj;TKMath;TKDraw;TKDCAF;TKBinTObj;TKXmlTObj"
)

# Create imported target TKQADraw
add_library(TKQADraw SHARED IMPORTED)

set_target_properties(TKQADraw PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/inc"
  INTERFACE_LINK_LIBRARIES "TKBRep;TKMath;TKernel;TKService;TKG2d;TKDraw;TKV3d;TKGeomBase;TKG3d;TKViewerTest;TKCDF;TKDCAF;TKLCAF;TKFillet;TKTopAlgo;TKHLR;TKBool;TKGeomAlgo;TKPrim;TKBO;TKShHealing;TKOffset;TKFeat;TKCAF;TKVCAF;TKIGES;TKXSBase;TKMesh;TKXCAF;TKBinXCAF;TKSTEP;TKSTEPBase;TKXDESTEP;TKXSDRAW;TKSTL;TKXml;TKTObj;TKXmlL;TKBin;TKBinL;TKStd;TKStdL;gdi32.lib;advapi32.lib;user32.lib"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/OpenCASCADEDrawTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "TKernel" "TKG2d" "TKGeomBase" "TKG3d" "TKMath" "TKBRep" "TKGeomAlgo" "TKShHealing" "TKMesh" "TKService" "TKHLR" "TKTopAlgo" "TKBO" "TKV3d" "TKFillet" "TKPrim" "TKBool" "TKOffset" "TKFeat" "TKOpenGl" "TKXSBase" "TKMeshVS" "TKSTEPBase" "TKSTEP" "TKIGES" "TKSTL" "TKVRML" "TKLCAF" "TKXCAF" "TKRWMesh" "TKCDF" "TKCAF" "TKVCAF" "TKStd" "TKStdL" "TKBin" "TKBinL" "TKXml" "TKXmlL" "TKXDE" "TKXDECascade" "TKXDEIGES" "TKXDESTEP" "TKBinXCAF" "TKXmlXCAF" "TKTObj" "TKBinTObj" "TKXmlTObj" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
